In [1]:
import pandas as pd
df = pd.read_csv('titanic.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [2]:
df.drop(['PassengerId', 'Name', 'SibSp', 'Parch', 'Ticket', 'Cabin', 'Embarked'], axis = 'columns' , inplace = True)
df.head()

   Survived  Pclass     Sex   Age     Fare
0         0       3    male  22.0   7.2500
1         1       1  female  38.0  71.2833
2         1       3  female  26.0   7.9250
3         1       1  female  35.0  53.1000
4         0       3    male  35.0   8.0500

In [3]:
target = df.Survived
inputs = df.drop('Survived' , axis = 'columns')

In [5]:
dummies = pd.get_dummies(inputs.Sex)
dummies.head(3)

   female   male
0   False   True
1    True  False
2    True  False

In [7]:
inputs = pd.concat([inputs, dummies], axis = 'columns')
inputs.head()

   Pclass     Sex   Age     Fare  female   male  female   male
0       3    male  22.0   7.2500   False   True   False   True
1       1  female  38.0  71.2833    True  False    True  False
2       3  female  26.0   7.9250    True  False    True  False
3       1  female  35.0  53.1000    True  False    True  False
4       3    male  35.0   8.0500   False   True   False   True

In [9]:
inputs.drop('Sex', axis ='columns', inplace = True)
inputs.head(3)

   Pclass   Age     Fare  female   male  female   male
0       3  22.0   7.2500   False   True   False   True
1       1  38.0  71.2833    True  False    True  False
2       3  26.0   7.9250    True  False    True  False

In [10]:
inputs.columns[inputs.isna().any()]

Index(['Age'], dtype='object')

In [11]:
inputs.Age[:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [13]:
inputs.Age = inputs.Age.fillna(inputs.Age.mean())
inputs.head(7)

   Pclass        Age     Fare  female   male  female   male
0       3  22.000000   7.2500   False   True   False   True
1       1  38.000000  71.2833    True  False    True  False
2       3  26.000000   7.9250    True  False    True  False
3       1  35.000000  53.1000    True  False    True  False
4       3  35.000000   8.0500   False   True   False   True
5       3  29.699118   8.4583   False   True   False   True
6       1  54.000000  51.8625   False   True   False   True

In [14]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(inputs, target , test_size = 0.2)

In [15]:
len(x_train)

712

In [16]:
len(x_test)

179

In [17]:
len(inputs)

891

In [19]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [20]:
model.fit(x_train , y_train)

GaussianNB()

In [21]:
model.score(x_test , y_test)

0.7932960893854749

In [22]:
x_test[:10]

     Pclass        Age     Fare  female   male  female   male
98        2  34.000000  23.0000    True  False    True  False
797       3  31.000000   8.6833    True  False    True  False
591       1  52.000000  78.2667    True  False    True  False
191       2  19.000000  13.0000   False   True   False   True
877       3  19.000000   7.8958   False   True   False   True
732       2  29.699118   0.0000   False   True   False   True
690       1  31.000000  57.0000   False   True   False   True
824       3   2.000000  39.6875   False   True   False   True
182       3   9.000000  31.3875   False   True   False   True
295       1  29.699118  27.7208   False   True   False   True

In [23]:
y_test[:10]

98     1
797    1
591    1
191    0
877    0
732    0
690    1
824    0
182    0
295    0
Name: Survived, dtype: int64

In [24]:
model.predict(x_test[:10])

array([1, 1, 1, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [25]:
model.predict_proba(x_test[:10])

array([[4.34578047e-04, 9.99565422e-01],
       [9.65710641e-04, 9.99034289e-01],
       [2.57620404e-05, 9.99974238e-01],
       [9.97942893e-01, 2.05710681e-03],
       [9.99066779e-01, 9.33220917e-04],
       [9.98247624e-01, 1.75237629e-03],
       [9.88903726e-01, 1.10962735e-02],
       [9.97607463e-01, 2.39253660e-03],
       [9.98513805e-01, 1.48619466e-03],
       [9.93511540e-01, 6.48846016e-03]])